### PR TITLE
[tabular] Fix Pandas 2.2 FutureWarning

### LINKED ISSUE #2904: [BUG] Tabular: FutureWarning
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [x] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
This is just a heads-up. I'm getting a FutureWarning (FutureWarning: Passing a set as an indexer is deprecated and will raise in a future version. Use a list instead.)  while running with feature_prune_kwargs={}. 

```

train_data_autogluon = TabularDataset(train_data)
val_data_autogluon = TabularDataset(val_data)
LABEL = "target"
print("Summary of class variable: \n", train_data_autogluon[LABEL].describe())
predictor = TabularPredictor(
    label=LABEL,
    eval_metric="roc_auc",
    path="/mnt/d/python_directory_2/models/model_hod_happened_test",
    verbosity=2,
).fit(
    feature_prune_kwargs={},
    train_data=train_data_autogluon,
    tuning_data=val_data_autogluon,
    hyperparameter_tune_kwargs='auto',
    ag_args_fit={'num_cpus': 8},
    hyperparameters={
        "GBM": [
            # {"extra_trees": True, "ag_args": {"name_suffix": "XT"}},
            {},
            # "GBMLarge",
        ],
    },
)
```

**Expected behavior**

**To Reproduce**
A minimal script to reproduce the issue. Links to Colab notebooks or similar tools are encouraged.  
If the code is too long, feel free to put it in a public gist and link it in the issue: https://gist.github.com.  
In short, we are going to copy-paste your code to run it and we expect to get the same result as you.

**Screenshots**

**Installed Versions**
Which version of AutoGluon are you are using?  
If you are using 0.4.0 and newer, please run the following code snippet:
<details>

```python
INSTALLED VERSIONS
------------------
date                   : 2023-02-13
time                   : 01:17:23.961549
python                 : 3.9.15.final.0
OS                     : Linux
OS-release             : 5.15.79.1-microsoft-standard-WSL2
Version                : #1 SMP Wed Nov 23 01:01:46 UTC 2022
machine                : x86_64
processor              : x86_64
num_cores              : 8
cpu_ram_mb             : 24037
cuda version           : 11.525.60.02
num_gpus               : 1
gpu_ram_mb             : [1870]
avail_disk_size_mb     : 68069

accelerate             : 0.13.2
albumentations         : 1.1.0
autogluon.common       : 0.6.2
autogluon.core         : 0.6.2
autogluon.features     : 0.6.2
autogluon.multimodal   : 0.6.2
autogluon.tabular      : 0.6.2
autogluon.text         : 0.6.2
autogluon.timeseries   : 0.6.2
autogluon.vision       : 0.6.2
boto3                  : 1.26.50
catboost               : 1.1.1
dask                   : 2023.1.1
defusedxml             : 0.7.1
distributed            : 2021.11.2
evaluate               : 0.3.0
fairscale              : 0.4.6
fastai                 : 2.7.10
gluoncv                : 0.11.0
gluonts                : 0.11.7
hyperopt               : 0.2.7
joblib                 : 1.2.0
jsonschema             : 4.8.0
lightgbm               : 3.3.4
matplotlib             : 3.6.2
networkx               : 2.8.8
nlpaug                 : 1.1.10
nltk                   : 3.8.1
nptyping               : 1.4.4
numpy                  : 1.23.5
omegaconf              : 2.1.2
openmim                : None
pandas                 : 1.5.2
PIL                    : 9.4.0
psutil                 : 5.9.4
pytorch-metric-learning: None
pytorch_lightning      : 1.7.7
ray                    : 2.0.1
requests               : 2.28.1
scipy                  : 1.10.0
sentencepiece          : 0.1.97
seqeval                : None
setuptools             : 65.6.3
skimage                : 0.19.3
sklearn                : 1.2.1
smart_open             : 5.2.1
statsmodels            : 0.13.5
text-unidecode         : None
timm                   : 0.6.12
torch                  : 1.12.1+cu102
torchmetrics           : 0.8.2
torchtext              : 0.13.1
torchvision            : 0.13.1+cu102
tqdm                   : 4.64.1
transformers           : 4.23.1
xgboost                : 1.7.3
```

</details>

**Additional context**

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*

Resolves #2904

*Description of changes:*
- Fix Pandas 2.2 FutureWarning

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Review by prateekdesai04 — APPROVED** [review]
LGTM!

**Pull request merged**
