### PR TITLE
Adding tutorial and related util functions for detection with dataframe

### PR DESCRIPTION
**Pull request by yongxinw**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Innixma** [comment]
@yongxinw Rebase with mainline and it should fix EDA unit test

**Review by FANGAreNotGnu — APPROVED** [review]
LGTM, thanks for the tutorial!

**Comment by yongxinw** [comment]
> LGTM, thanks for the tutorial!

Thanks for the review!

**Review by bryanyzhu — APPROVED** [review]
LGTM, thank you for adding this feature.

**Pull request merged**
