### PR TITLE
[DO NOT MERGE] Upgrade pandas to 2.2.x

### LINKED ISSUE #3989: Support Pandas 2.2
Currently the pandas version is limited to <2.2. Please support pandas 2.2.x as well.

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*

Resolves #3989 

*Description of changes:*

Upgrade Pandas from <2.2 to <2.3

TODO:

- [ ] Currently testing 2.2 support, will set the final version range to `>=2.0,<2.3` prior to merge.
- [ ] @Innixma Verify status of Tabular support
- [ ] @shchur Verify status of TimeSeries support (https://github.com/autogluon/autogluon/pull/4024#discussion_r1553678391)
- [ ] @zhiqiangdon Verify status of AutoMM support

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |
| vowpalwabbit==9.8.0 | vowpalwabbit==9.9.0 |
| skl2onnx==1.15.0 | skl2onnx==1.16.0 |
| vowpalwabbit==9.8.0 | vowpalwabbit==9.9.0 |
| skl2onnx==1.15.0 | skl2onnx==1.16.0 |

**Comment by tonyhoo** [comment]
> Previous CI Run	Current CI Run
> vowpalwabbit==9.8.0	vowpalwabbit==9.9.0
> skl2onnx==1.15.0	skl2onnx==1.16.0
> vowpalwabbit==9.8.0	vowpalwabbit==9.9.0
> skl2onnx==1.15.0	skl2onnx==1.16.0

@prateekdesai04  any clue why `pandas` not showing up here?

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by Innixma** [comment]
Replaced by #4079

**Pull request closed without merging**
