### PR TITLE
[Merge after 0.6.1]Update collator names

### PR DESCRIPTION
**Pull request by zhiqiangdon**
*Issue #, if available:*
Some previous collator names, e.g., Dict and List, have conflicts with the type hint names.

*Description of changes:*
Update the collator names to avoid the conflicts.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by cheungdaven — APPROVED** [review]
LGTM!

**Review by suzhoum — APPROVED** [review]
LGTM!

**Review by bryanyzhu — APPROVED** [review]
Nice refactor, LGTM

**Review by sxjscience — APPROVED** [review]
LGTM

**Pull request merged**
