### PR TITLE
[timeseries] revert random seed fix (#3934)

### PR DESCRIPTION
**Pull request by canerturkmen**
Draft PR, test reversion of commit ab7355500fb40b7362f0b9717b6e3d5e9971c66a.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by shchur** [comment]
Replaced by #4099

**Pull request closed without merging**
