### PR TITLE
[multimodal] Fix mmcv reference if import failed

### PR DESCRIPTION
**Pull request by FANGAreNotGnu**
Error message that guide user to install mmcv won't print before this fix.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by zhiqiangdon — COMMENTED** [review]
Before this fix, what would happen if mmcv is not installed?

**Comment by FANGAreNotGnu** [comment]
> Before this fix, what would happen if mmcv is not installed?

The mmcv will not be imported when we init the dataset and the error will raise for the line `model_config: mmcv.utils.config.Config,`.

**Review by zhiqiangdon — COMMENTED** [review]
CI is not passed.

**Comment by FANGAreNotGnu** [comment]
> CI is not passed.

Fixed. It was because the import code was wrong.

**Review by zhiqiangdon — APPROVED** [review]
LGTM

**Pull request merged**
