### PR TITLE
[multimodal] Update torchmetrics map

### PR DESCRIPTION
**Pull request by FANGAreNotGnu**
Use latest implementation if `torchmetrics.__version__ > 0.11.0`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by bryanyzhu — APPROVED** [review]
Code looks good. One question, after switching to using torchmetrics 0.11.0, will performance on several datasets/tutorials change?

**Comment by sxjscience** [comment]
Shall we just upgrade torchmetrics (make it >=0.11.0?) I think @zhiqiangdon mentioned that there is another issue about `pos_label`

**Comment by FANGAreNotGnu** [comment]
> Shall we just upgrade torchmetrics (make it >=0.11.0?) I think @zhiqiangdon mentioned that there is another issue about `pos_label`

I think 0.11.0 is not ok for map since the bug is fixed in 0.11.1. I update this so that we don't need to force the version >=0.11.1.

**Comment by FANGAreNotGnu** [comment]
> Code looks good. One question, after switching to using torchmetrics 0.11.0, will performance on several datasets/tutorials change?

I tested the two versions of map implementation on two datasets and they performs similarly. I haven't done a speed analysis on heavy task but the latest one is at least not slower than the previous one.

**Comment by FANGAreNotGnu** [comment]
Tried on COCO17 val split. Both implementations output the same result for `checkpoint_name = yolov3_mobilenetv2_320_300e_coco` and in about the same time (0.11.1 takes 340 seconds and previous one takes 352 seconds). @bryanyzhu @sxjscience

**Review by sxjscience — APPROVED** [review]
LGTM

**Comment by sxjscience** [comment]
Do we need to directly upgrade torchmetrics so that the logic can be more clean.

**Pull request merged**
