### PR TITLE
[docs] [timeseries] add Chronos tutorial and citation

### PR DESCRIPTION
**Pull request by canerturkmen**
*Issue #, if available:*

*Description of changes:*
- Add Chronos tutorial and citation. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |
| matplotlib-inline==0.1.6 | matplotlib-inline==0.1.7 |
| matplotlib-inline==0.1.6 | matplotlib-inline==0.1.7 |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Review by shchur — APPROVED** [review]
LGTM!

**Pull request merged**
