### PR TITLE
[timeseries] Upgrade GluonTS to v0.15.1

### PR DESCRIPTION
**Pull request by shchur**
*Description of changes:*
- Bump GluonTS dependency to v0.15.1
- Add wrapper for the `TiDE` model

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by shchur** [comment]
We have detected some bugs in GluonTS v0.15.0. Waiting for the GluonTS v0.15.1 release that will include the hotfix (https://github.com/awslabs/gluonts/pull/3191) — ETA Monday, June 3.

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |
| fastcore==1.5.42 | fastcore==1.5.43 |
| types-requests==2.32.0.20240523 | types-requests==2.32.0.20240602 |
| certifi==2024.2.2 | certifi==2024.6.2 |
| typing_extensions==4.12.0 | typing_extensions==4.12.1 |
| fastcore==1.5.42 | fastcore==1.5.43 |
| types-requests==2.32.0.20240523 | types-requests==2.32.0.20240602 |
| certifi==2024.2.2 | certifi==2024.6.2 |
| typing_extensions==4.12.0 | typing_extensions==4.12.1 |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Review by canerturkmen — APPROVED** [review]
Yay! 🙌

**Pull request merged**
