### PR TITLE
[AutoMM] Update conv-lora readme

### PR DESCRIPTION
**Pull request by zhiqiangdon**
*Issue #, if available:*

*Description of changes:*
Update readme by putting the installation at the beginning since downloading the datasets also requires the installation.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |
| pyasn1==0.5.1 | pyasn1==0.6.0 |
| botocore==1.34.70 | botocore==1.34.71 |
| pyasn1-modules==0.3.0 | - |
| huggingface-hub==0.22.0 | huggingface-hub==0.22.1 |
| boto3==1.34.70 | boto3==1.34.71 |
| - | pyasn1_modules==0.4.0 |
| pyasn1==0.5.1 | pyasn1==0.6.0 |
| botocore==1.34.70 | botocore==1.34.71 |
| huggingface-hub==0.22.0 | huggingface-hub==0.22.1 |
| boto3==1.34.70 | boto3==1.34.71 |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Review by prateekdesai04 — APPROVED** [review]
LGTM!

**Review by Harry-zzh — APPROVED** [review]
LGTM

**Pull request merged**
