### PR TITLE
[tabular] Add roc_auc_ovo / ovr

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*

*Description of changes:*

- Add roc_auc_ovo metrics
- Add roc_auc_ovr metrics
- Remove roc_auc_ovo_macro from binary metrics (not a binary metric) 
- Raise exception if inferred problem_type mismatches eval_metric.
- Improve logging when metric related errors occur (invalid metric specified)  
- Fix edge-case crash / incorrect metric calculation in multiclass when rare classes are dropped at fit time and then leaderboard is called with those rare classes and extra_metrics specified.

TODO:

- [x] Fix unit tests, edge cases are not handled
- [x] Address FIXME comments
- [x] [Fixed] See if log loss is bugged for rare classes when passing `extra_metrics`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by suzhoum — APPROVED** [review]
LTGM!

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |
| botocore==1.34.123 | botocore==1.34.124 |
| boto3==1.34.123 | boto3==1.34.124 |
| botocore==1.34.123 | botocore==1.34.124 |
| boto3==1.34.123 | boto3==1.34.124 |

**Pull request merged**
