### PR TITLE
Documentation - Install AG in Kaggle

### PR DESCRIPTION
**Pull request by bryanyzhu**
*Issue #, if available:*
#2777 #2572 #2870 

*Description of changes:*
Add documentation to inform users how to upgrade python version in Kaggle in order to correctly install AutoGluon.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Innixma** [comment]
Thanks for creating these instructions! I think if we were to make a video series on quick guides & tutorials for AutoGluon, a short 1-2 minute video on this would be a great candidate

**Comment by Innixma** [comment]
I created #2872 to document the video idea, and noted Kaggle tutorial as one of the options

**Review by Innixma — APPROVED** [review]
Approving assuming formatting is correct (ex: can see the code block)

**Comment by bryanyzhu** [comment]
> Approving assuming formatting is correct (ex: can see the code block)

Thanks for approving, the code block can be seen now.

**Pull request merged**
