### PR TITLE
Add v1.1.0 Release Notes

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*

*Description of changes:*

- Add v1.1.0 Release Notes

TODO:

- [x] Intro @Innixma
- [x] Kaggle Results Highlight @Innixma
- [x] Chronos Highlight @shchur @canerturkmen 
- [x] AutoMM Section @zhiqiangdon 
- [x] TimeSeries Section @shchur @canerturkmen 
- [x] Individual PR Notes @Innixma 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by shchur** [comment]
@Innixma I will update the TS section by 11am PT today.

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |
| orjson==3.10.0 | orjson==3.10.1 |
| orjson==3.10.0 | orjson==3.10.1 |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Pull request merged**
