### PR TITLE
Add multimodal cheatsheet

### PR DESCRIPTION
**Pull request by sxjscience**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by bryanyzhu — APPROVED** [review]
Looks good.

**Comment by tonyhoo** [comment]
LGTM

**Review by tonyhoo — APPROVED** [review]

**Review by zhiqiangdon — APPROVED** [review]
LGTM!

**Review by FANGAreNotGnu — APPROVED** [review]
LGTM!

**Review by Innixma — CHANGES_REQUESTED** [review]
Lets add the image file to autogluon-doc-utils (my repo), that way we don't unnecessarily bloat the autogluon repo's size.

**Comment by sxjscience** [comment]
We now have figures + pdf files in S3:

- PNG: https://automl-mm-bench.s3-accelerate.amazonaws.com/cheatsheet/v0.6.0/AutoGluon_Multimodal_Cheatsheet_v0.6.0.png
- PDF: https://automl-mm-bench.s3-accelerate.amazonaws.com/cheatsheet/v0.6.0/AutoGluon_Multimodal_Cheatsheet_v0.6.0.pdf

**Review by Innixma — APPROVED** [review]
LGTM! We will want to revise where we store the png beyond S3 so we have versioning in future. I'd suggest autogluon-doc-utils

**Pull request merged**
