### PR TITLE
[timeseries] use chronos test fixture in smoke tests

### PR DESCRIPTION
**Pull request by canerturkmen**
*Issue #, if available:*

*Description of changes:*

Previously time series smoke tests and model tests did not reuse the `hf_model_path` test fixture, leading to about ~250 downloads on Hugging Face for each CI run. This PR brings the number to about ~10~ 40. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Review by shchur — APPROVED** [review]
LGTM! Only some minor questions

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Pull request merged**
