### PR TITLE
Tabular: Switched KNN and RF to use refit_folds instead of use_child_oof

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*

*Description of changes:*

- Switched KNN and RF to use refit_folds instead of use_child_oof during bagging
- This results in the same model at test time for RF and KNN, but different out of fold predictions.
- While being 10x slower to train, this will reduce stack information leakage significantly while keeping inference speed identical. I would guess that assuming enough time is given, this will improve stack quality.

TODO:

- [ ] Benchmark

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by szha** [comment]
Job PR-1351-1 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1351/1/index.html

**Comment by szha** [comment]
Job PR-1351-3 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1351/3/index.html

**Comment by szha** [comment]
Job PR-1351-5 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1351/5/index.html

**Comment by szha** [comment]
Job PR-1351-8 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1351/8/index.html

**Comment by szha** [comment]
Job PR-1351-9 is done. 
Docs are uploaded to http://autogluon-staging.s3-website-us-west-2.amazonaws.com/PR-1351/9/index.html

**Comment by Innixma** [comment]
Closing due to being outdated and not showing superior performance to `use_child_oof`.

**Pull request closed without merging**
