### PR TITLE
[timeseries] Update to GluonTS v0.12.0

### PR DESCRIPTION
**Pull request by shchur**
*Description of changes:*
- Add TFT PyTorch model
- Update the SFF model (use StudentT output, fix the quantile workaround)
- Drop the `Prophet` GluonTS wrapper

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by canerturkmen — COMMENTED** [review]
LGTM. Can we rebase and rerun tests?

**Comment by shchur** [comment]
@canerturkmen Cannot run the tests on CI until GluonTS v0.12.0 is released on PyPI, unfortunately. Will do that tomorrow after the release

**Comment by shchur** [comment]
@canerturkmen 
- I have removed the prophet model (it's anyway currently completely unusable since it's not included in `MODEL_TYPES` in [presets.py](https://github.com/autogluon/autogluon/blob/master/timeseries/src/autogluon/timeseries/models/presets.py#L29))
- ran the tests locally with the latest version of GluonTS `master` branch (see screenshot)

gluonts_v012_tests_report

**Review by canerturkmen — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
