### PR TITLE
[WIP] Add Python 3.10 Support

### PR DESCRIPTION
**Pull request by Innixma**
*Issue #, if available:*
#2686 

*Description of changes:*
- WIP PR to add Python 3.10 Support, currently untested

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by gradientsky — APPROVED** [review]

**Comment by Innixma** [comment]
@yinweisu How should I properly ensure Python 3.10 is being testing in the CI?

**Comment by yinweisu** [comment]
I believe the docker image our CI is using is on python 3.8 as we use DLC container as the base.
We might be able to update the python version. @gradientsky Any advice?

**Comment by gradientsky** [comment]
Tested:
- tabular on M1 mac (build from sources from `master`);
- tabular/time series/automm with `autogluon==0.6.3b20230118` in containers. No issues.

<details>
<summary><b><u>Details - Fit Summary in Linux</u></b></summary>

```
(.venv) (py310) root@testbox:/# python --version
Python 3.10.8
(.venv) (py310) root@testbox:/# pip freeze | grep autogluon
autogluon==0.6.3b20230118
autogluon.common==0.6.3b20230118
autogluon.core==0.6.3b20230118
autogluon.features==0.6.3b20230118
autogluon.multimodal==0.6.3b20230118
autogluon.tabular==0.6.3b20230118
autogluon.text==0.6.3b20230118
autogluon.timeseries==0.6.3b20230118
autogluon.vision==0.6.3b20230118
(.venv) (py310) root@testbox:/# ipython
/opt/conda/lib/python3.8/site-packages/IPython/core/interactiveshell.py:820: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
  warn(
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from autogluon.tabular import TabularDataset, TabularPredictor
   ...: train_data = TabularDataset('https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
   ...: subsample_size = 500  # subsample subset of data for faster demo, try setting this to much larger values
   ...: train_data = train_data.sample(n=subsample_size, random_state=0)
   ...: label = 'class'
   ...: print("Summary of class variable: \n", train_data[label].describe())
   ...: save_path = 'agModels-predictClass'  # specifies folder to store trained models
   ...: predictor = TabularPredictor(label=label, path=save_path).fit(train_data)
   ...: test_data = TabularDataset('https://autogluon.s3.amazonaws.com/datasets/Inc/test.csv')
   ...: y_test = test_data[label]  # values to predict
   ...: test_data_nolab = test_data.drop(columns=[label])  # delete label column to prove we're not cheating
   ...: test_data_nolab.head()
   ...: predictor = TabularPredictor.load(save_path)  # unnecessary, just demonstrates how to load previously-trained predictor from file
   ...:
   ...: y_pred = predictor.predict(test_data_nolab)
   ...: print("Predictions:  \n", y_pred)
   ...: perf = predictor.evaluate_predictions(y_true=y_test, y_pred=y_pred, auxiliary_metrics=True)
   ...: predictor.leaderboard(test_data, silent=True)
Summary of class variable:
 count        500
unique         2
top        <=50K
freq         365
Name: class, dtype: object
Beginning AutoGluon training ...
AutoGluon will save models to "agModels-predictClass/"
AutoGluon Version:  0.6.1
Python Version:     3.8.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #26~20.04.1-Ubuntu SMP Sat Oct 15 03:22:07 UTC 2022
Train Data Rows:    500
Train Data Columns: 14
Label Column: class
Preprocessing data ...
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [' >50K', ' <=50K']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
Selected class <--> label mapping:  class 1 =  >50K, class 0 =  <=50K
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive ( >50K) vs negative ( <=50K) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    31880.09 MB
	Train Data (Original)  Memory Usage: 0.29 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', [])    : 6 | ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', ...]
		('object', []) : 8 | ['workclass', 'education', 'marital-status', 'occupation', 'relationship', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 7 | ['workclass', 'education', 'marital-status', 'occupation', 'relationship', ...]
		('int', [])       : 6 | ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', ...]
		('int', ['bool']) : 1 | ['sex']
	0.1s = Fit runtime
	14 features in original data used to generate 14 features in processed data.
	Train Data (Processed) Memory Usage: 0.03 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.07s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 400, Val Rows: 100
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.73	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.65	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMXT ...
	0.83	 = Validation score   (accuracy)
	0.68s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ...
	0.85	 = Validation score   (accuracy)
	0.23s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.84	 = Validation score   (accuracy)
	0.54s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.83	 = Validation score   (accuracy)
	0.45s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.85	 = Validation score   (accuracy)
	0.91s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.82	 = Validation score   (accuracy)
	0.45s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.81	 = Validation score   (accuracy)
	0.45s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
[2023-01-18 17:09:24.539: W smdistributed/modelparallel/torch/nn/predefined_hooks.py:78] Found unsupported HuggingFace version 4.23.1 for automated tensor parallelism. HuggingFace modules will not be automatically distributed. You can use smp.tp_register_with_module API to register desired modules for tensor parallelism, or directly instantiate an smp.nn.DistributedModule. Supported HuggingFace transformers versions for automated tensor parallelism: ['4.17.0', '4.20.1', '4.21.0']
[2023-01-18 17:09:24.624 testbox:365 INFO utils.py:28] RULE_JOB_STOP_SIGNAL_FILENAME: None
/opt/conda/lib/python3.8/site-packages/smdebug-1.0.24b20230106-py3.8.egg/smdebug/profiler/system_metrics_reader.py:78: SyntaxWarning: "is not" with a literal. Did you mean "!="?
/opt/conda/lib/python3.8/site-packages/smdebug-1.0.24b20230106-py3.8.egg/smdebug/profiler/system_metrics_reader.py:78: SyntaxWarning: "is not" with a literal. Did you mean "!="?
[2023-01-18 17:09:24.768 testbox:365 INFO profiler_config_parser.py:111] Unable to find config at /opt/ml/input/config/profilerconfig.json. Profiler is disabled.
	0.82	 = Validation score   (accuracy)
	9.86s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: XGBoost ...
	0.87	 = Validation score   (accuracy)
	0.21s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.83	 = Validation score   (accuracy)
	1.08s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.83	 = Validation score   (accuracy)
	0.42s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	0.87	 = Validation score   (accuracy)
	0.38s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 16.16s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("agModels-predictClass/")
Loaded data from: https://autogluon.s3.amazonaws.com/datasets/Inc/test.csv | Columns = 15 / 15 | Rows = 9769 -> 9769
Predictions:
 0        <=50K
1        <=50K
2        <=50K
3        <=50K
4        <=50K
         ...
9764     <=50K
9765     <=50K
9766     <=50K
9767     <=50K
9768     <=50K
Name: class, Length: 9769, dtype: object
Evaluation: accuracy on test data: 0.8374449790152523
Evaluations on test data:
{
    "accuracy": 0.8374449790152523,
    "balanced_accuracy": 0.7430558394221018,
    "mcc": 0.5243657567117436,
    "f1": 0.621904761904762,
    "precision": 0.69394261424017,
    "recall": 0.5634167385677308
}
Out[1]:
                  model  score_test  score_val  pred_time_test  pred_time_val  ...  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0      RandomForestGini    0.842870       0.84        0.257703       0.053655  ...                0.053655           0.536125            1       True          5
1              CatBoost    0.842461       0.85        0.012896       0.005087  ...                0.005087           0.909912            1       True          7
2      RandomForestEntr    0.841130       0.83        0.133782       0.054296  ...                0.054296           0.451478            1       True          6
3              LightGBM    0.839799       0.85        0.018522       0.005228  ...                0.005228           0.233378            1       True          4
4               XGBoost    0.837445       0.87        0.068974       0.005073  ...                0.005073           0.213027            1       True         11
5   WeightedEnsemble_L2    0.837445       0.87        0.071998       0.005642  ...                0.000569           0.381432            2       True         14
6            LightGBMXT    0.836421       0.83        0.013960       0.005702  ...                0.005702           0.679621            1       True          3
7        ExtraTreesGini    0.834579       0.82        0.134767       0.051691  ...                0.051691           0.450471            1       True          8
8        NeuralNetTorch    0.833555       0.83        0.108382       0.014971  ...                0.014971           1.077395            1       True         12
9        ExtraTreesEntr    0.833350       0.81        0.134604       0.053992  ...                0.053992           0.447923            1       True          9
10        LightGBMLarge    0.828949       0.83        0.028656       0.005984  ...                0.005984           0.418561            1       True         13
11      NeuralNetFastAI    0.818610       0.82        0.145741       0.015086  ...                0.015086           9.858974            1       True         10
12       KNeighborsUnif    0.725970       0.73        0.034486       0.007386  ...                0.007386           0.015174            1       True          1
13       KNeighborsDist    0.695158       0.65        0.039881       0.005815  ...                0.005815           0.008111            1       True          2

[14 rows x 12 columns]

In [2]: import mxnet
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ <ipython-input-2-1eadd2d362f9>:1 in <cell line: 1>                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'mxnet'

   ...:
   ...: df = pd.read_csv(
   ...:     "https://autogluon.s3-us-west-2.amazonaws.com/datasets/CovidTimeSeries/train.csv",
   ...:     parse_dates=["Date"],
   ...: )
   ...:
   ...: data = TimeSeriesDataFrame.from_data_frame(
   ...:     df,
   ...:     id_column="name",
   ...:     timestamp_column="Date",
   ...: )
   ...: # Select the first 50 time series for faster training
   ...: data = data.loc[data.item_ids[:50]]
   ...:
   ...: prediction_length = 5
   ...: target_column = "ConfirmedCases"
   ...:
   ...: # known covariates
   ...: data["weekend"] = data.index.get_level_values("timestamp").weekday.isin([5, 6]).astype(float)
   ...: # use item id as static features
   ...: static_features = data.index.unique("item_id").to_frame()
   ...: static_features.columns = ["CountryName"]
   ...: data.static_features = static_features
   ...:
   ...: test_data = data.copy()
   ...: train_data = data.slice_by_timestep(None, -prediction_length)
   ...:
   ...: predictor = TimeSeriesPredictor(
   ...:     path="autogluon-covidforecast",
   ...:     target=target_column,
   ...:     prediction_length=prediction_length,
   ...:     eval_metric="sMAPE",
   ...:     known_covariates_names=["weekend"],
   ...: )
   ...: predictor.fit(
   ...:     train_data,
   ...:     hyperparameters={
   ...:         "Naive": {},
   ...:         "SeasonalNaive": {},
   ...:         "ETS": {},
   ...:         "ARIMA": {},
   ...:         "AutoGluonTabular": {},
   ...:         "DeepAR": {"epochs": 5, "num_batches_per_epoch": 5},
   ...:     },
   ...: )
   ...:
   ...: predictor.leaderboard()
   ...: predictor.leaderboard(test_data)
   ...:
   ...: known_covariates = test_data.drop(target_column, axis=1)
   ...: print(predictor.predict(train_data, known_covariates=known_covariates).head(5))
   ...: print(predictor.score(test_data))
   ...:
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmpjypxf6cg
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmpjypxf6cg/_remote_module_non_scriptable.py
================ TimeSeriesPredictor ================
TimeSeriesPredictor.fit() called
Fitting with arguments:
{'enable_ensemble': True,
 'evaluation_metric': 'sMAPE',
 'hyperparameter_tune_kwargs': None,
 'hyperparameters': {'ARIMA': {},
                     'AutoGluonTabular': {},
                     'DeepAR': {'epochs': 5, 'num_batches_per_epoch': 5},
                     'ETS': {},
                     'Naive': {},
                     'SeasonalNaive': {}},
 'prediction_length': 5,
 'random_seed': None,
 'target': 'ConfirmedCases',
 'time_limit': None}
Provided training data set with 3350 rows, 50 items (item = single time series). Average time series length is 67.0.
Training artifacts will be saved to: /autogluon-covidforecast
=====================================================
AutoGluon will save models to autogluon-covidforecast/
AutoGluon will gauge predictive performance using evaluation metric: 'sMAPE'
	This metric's sign has been flipped to adhere to being 'higher is better'. The reported score can be multiplied by -1 to get the metric value.
Following types of static features have been inferred:
	categorical: ['CountryName']
	continuous (float): []
To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit
tuning_data is None. Will use the last prediction_length = 5 time steps of each time series as a hold-out validation set.

Starting training. Start time is 2023-01-18 17:10:20
Models that will be trained: ['Naive', 'SeasonalNaive', 'ETS', 'ARIMA', 'AutoGluonTabular', 'DeepAR']
Training timeseries model Naive.
	-0.4893       = Validation score (-sMAPE)
	0.00    s     = Training runtime
	4.70    s     = Validation (prediction) runtime
Training timeseries model SeasonalNaive.
	-1.2023       = Validation score (-sMAPE)
	0.01    s     = Training runtime
	0.15    s     = Validation (prediction) runtime
Training timeseries model ETS.
	-0.3057       = Validation score (-sMAPE)
	0.00    s     = Training runtime
	1.15    s     = Validation (prediction) runtime
Training timeseries model ARIMA.
	-0.3670       = Validation score (-sMAPE)
	0.00    s     = Training runtime
	1.98    s     = Validation (prediction) runtime
Training timeseries model AutoGluonTabular.
	-1.1783       = Validation score (-sMAPE)
	3.09    s     = Training runtime
	0.48    s     = Validation (prediction) runtime
Training timeseries model DeepAR.
	-1.6589       = Validation score (-sMAPE)
	6.30    s     = Training runtime
	0.39    s     = Validation (prediction) runtime
Fitting simple weighted ensemble.
	-0.3044       = Validation score (-sMAPE)
	6.34    s     = Training runtime
	5.85    s     = Validation (prediction) runtime
Training complete. Models trained: ['Naive', 'SeasonalNaive', 'ETS', 'ARIMA', 'AutoGluonTabular', 'DeepAR', 'WeightedEnsemble']
Total runtime: 25.83 s
Best model: WeightedEnsemble
Best model score: -0.3044
              model  score_val  pred_time_val  fit_time_marginal  fit_order
0  WeightedEnsemble  -0.304370       5.849872           6.344286          7
1               ETS  -0.305652       1.145810           0.004459          3
2             ARIMA  -0.366951       1.975837           0.003824          4
3             Naive  -0.489305       4.704062           0.003894          1
4  AutoGluonTabular  -1.178310       0.483262           3.086395          5
5     SeasonalNaive  -1.202335       0.153004           0.008596          2
6            DeepAR  -1.658883       0.387928           6.296982          6
Additional data provided, testing on additional data. Resulting leaderboard will be sorted according to test score (`score_test`).
              model  score_test  score_val  pred_time_test  pred_time_val  fit_time_marginal  fit_order
0  WeightedEnsemble   -0.215784  -0.304370        1.381786       5.849872           6.344286          7
1               ETS   -0.218634  -0.305652        1.240347       1.145810           0.004459          3
2             ARIMA   -0.233639  -0.366951        2.003569       1.975837           0.003824          4
3             Naive   -0.368258  -0.489305        0.141152       4.704062           0.003894          1
4     SeasonalNaive   -0.907745  -1.202335        0.141859       0.153004           0.008596          2
5  AutoGluonTabular   -1.190523  -1.178310        0.426125       0.483262           3.086395          5
6            DeepAR   -1.523418  -1.658883        0.701585       0.387928           6.296982          6
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble
                               mean         0.1         0.2         0.3         0.4         0.5         0.6         0.7         0.8         0.9
item_id      timestamp
Afghanistan_ 2020-03-29  120.290060  114.845897  116.714766  118.062353  119.213816  120.290060  121.366305  122.517768  123.865355  125.734224
             2020-03-30  124.304428  115.622153  118.602599  120.751711  122.588048  124.304428  126.020807  127.857144  130.006256  132.986703
             2020-03-31  131.329037  118.158471  122.679656  125.939748  128.725377  131.329037  133.932697  136.718326  139.978419  144.499604
             2020-04-01  135.818084  117.291300  123.651165  128.237074  132.155565  135.818084  139.480603  143.399093  147.985003  154.344867
             2020-04-02  140.038368  115.461721  123.898380  129.981804  135.179865  140.038368  144.896872  150.094933  156.178357  164.615015
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble
-0.215783703267195

In [4]: exit
(.venv) (py310) root@testbox:/# ipython
/opt/conda/lib/python3.8/site-packages/IPython/core/interactiveshell.py:820: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
  warn(
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.1.0 -- An enhanced Interactive Python. Type '?' for help.

   ...:         "env.num_gpus": 1,
   ...:     },
   ...:     time_limit=20, # seconds
   ...: )
   ...:
   ...: scores = predictor.evaluate(test_data, metrics=["accuracy"])
   ...: print(scores)
   ...:
   ...: from autogluon.multimodal import AutoMMPredictor
   ...: predictor = AutoMMPredictor(label=label_col)
   ...: predictor.fit(
   ...:     train_data=train_data,
   ...:     hyperparameters={
   ...:         "model.names": ["clip", "timm_image", "hf_text", "numerical_mlp", "fusion_mlp"],
   ...:         "model.timm_image.checkpoint_name": "swin_small_patch4_window7_224",
   ...:         "model.hf_text.checkpoint_name": "google/electra-small-discriminator",
   ...:         "env.num_gpus": 1,
   ...:     },
   ...:     time_limit=20, # seconds
   ...: )
   ...:
   ...: scores = predictor.evaluate(test_data, metrics=["accuracy"])
   ...: print(scores)
   ...:
   ...: from autogluon.multimodal import AutoMMPredictor
   ...: predictor = AutoMMPredictor(label=label_col)
   ...: predictor.fit(
   ...:     train_data=train_data,
   ...:     hyperparameters={
   ...:         "model.names": ["timm_image"],
   ...:         "model.timm_image.checkpoint_name": "swin_tiny_patch4_window7_224",
   ...:         "env.num_gpus": 1,
   ...:     },
   ...:     time_limit=20, # seconds
   ...: )
   ...:
   ...: scores = predictor.evaluate(test_data, metrics=["accuracy"])
   ...: print(scores)
   ...:
   ...: from autogluon.multimodal import AutoMMPredictor
   ...: predictor = AutoMMPredictor(label=label_col)
   ...: predictor.fit(
   ...:     train_data=train_data,
   ...:     hyperparameters={
   ...:         "model.names": ["hf_text"],
   ...:         "model.hf_text.checkpoint_name": "google/electra-small-discriminator",
   ...:         "env.num_gpus": 1,
   ...:     },
   ...:     time_limit=20, # seconds
   ...: )
   ...:
   ...: scores = predictor.evaluate(test_data, metrics=["accuracy"])
   ...: print(scores)
Downloading ./ag_automm_tutorial/file.zip from https://automl-mm-bench.s3.amazonaws.com/petfinder_kaggle.zip...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.00G/2.00G [00:49<00:00, 40.7MiB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.19k/4.19k [00:00<00:00, 3.92MB/s]
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 605M/605M [00:05<00:00, 106MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 862k/862k [00:00<00:00, 83.5MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 525k/525k [00:00<00:00, 77.5MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 322kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 568/568 [00:00<00:00, 471kB/s]
Downloading /opt/conda/lib/python3.8/site-packages/autogluon/multimodal/data/templates.zip from https://automl-mm-bench.s3.amazonaws.com/few_shot/templates.zip...
Sanity Checking: 0it [00:00, ?it/s][2023-01-18 17:12:44.720: W smdistributed/modelparallel/torch/nn/predefined_hooks.py:78] Found unsupported HuggingFace version 4.23.1 for automated tensor parallelism. HuggingFace modules will not be automatically distributed. You can use smp.tp_register_with_module API to register desired modules for tensor parallelism, or directly instantiate an smp.nn.DistributedModule. Supported HuggingFace transformers versions for automated tensor parallelism: ['4.17.0', '4.20.1', '4.21.0']
[2023-01-18 17:12:44.758 99405d27271b:725 INFO utils.py:28] RULE_JOB_STOP_SIGNAL_FILENAME: None
[2023-01-18 17:12:44.894 99405d27271b:725 INFO profiler_config_parser.py:111] Unable to find config at /opt/ml/input/config/profilerconfig.json. Profiler is disabled.
Epoch 1:  18%|█████████████████████▋                                                                                                | 14/76 [00:36<02:41,  2.60s/it, loss=1.54, v_num=]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  7.48it/s]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  7.35it/s]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  6.91it/s]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  6.75it/s]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  6.75it/s]
{'accuracy': 0.29}
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 665/665 [00:00<00:00, 712kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 54.2M/54.2M [00:00<00:00, 89.5MB/s]
Downloading: "https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_small_patch4_window7_224.pth" to /root/.cache/torch/hub/checkpoints/swin_small_patch4_window7_224.pth
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29.0/29.0 [00:00<00:00, 30.6kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 58.9MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 466k/466k [00:00<00:00, 73.3MB/s]
Epoch 0:  68%|████████████████████████████████████████████████████████████████████████████████▋                                     | 52/76 [01:21<00:37,  1.58s/it, loss=2.96, v_num=]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.54it/s]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.46it/s]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.38it/s]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.25it/s]
{'accuracy': 0.16}
Downloading: "https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth" to /root/.cache/torch/hub/checkpoints/swin_tiny_patch4_window7_224.pth
Epoch 1:  79%|█████████████████████████████████████████████████████████████████████████████████████████████▉                         | 60/76 [00:12<00:03,  4.64it/s, loss=1.4, v_num=]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  6.56it/s]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  6.54it/s]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  6.52it/s]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  6.33it/s]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  6.46it/s]
{'accuracy': 0.19}
Epoch 2:  39%|██████████████████████████████████████████████▌                                                                       | 30/76 [00:04<00:06,  7.40it/s, loss=1.45, v_num=]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  6.58it/s]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  6.61it/s]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  6.36it/s]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  6.69it/s]
Predicting DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00,  6.17it/s]
{'accuracy': 0.17}
```
</details>

**Comment by gradientsky** [comment]
> We might be able to update the python version. @gradientsky Any advice?

We need to carry all python versions we supporting in the containers; this will enable multi-version testing. Since the new containers are pytorch-based with conda; we can just create multiple conda environments with different versions. tox can use all of them and run tests during the builds.

**Pull request merged**
