### PR TITLE
[Tutorial] Add Installation Guide for Object Detection in Tutorial

### PR DESCRIPTION
**Pull request by FANGAreNotGnu**
https://github.com/autogluon/autogluon/issues/3963

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by suzhoum — APPROVED** [review]
LGTM！

**Review by Innixma — APPROVED** [review]
LGTM assuming website build shows the cells properly

**Comment by Innixma** [comment]
/benchmark module=tabular preset=tabular_best benchmark=tabular_full time_limit=1h

**Comment by Innixma** [comment]
(above comment is for testing, can disregard)

**Pull request merged**
