### PR TITLE
[multimodal] undo changes to num_workers

### PR DESCRIPTION
**Pull request by liangfu**
*Issue #, if available:*

#2756

*Description of changes:*

The root cause of the issue is that https://github.com/autogluon/autogluon/commit/93fcbb955eb628b6896b8d277386a4c9a9345384 changed num_workers=2

Here is a visualization before and after the change #2416 that could affect the overall evaluation time of beginner_image_cls.ipynb .

image

By removing ‘num_workers=2’, we can reduce predictor.fit from 206 seconds to 128 seconds. Training throughput increased from 3.92s/it to 0.68s/it (aka 1.46it/s).

Code to reproduce the results

```python
import pandas as pd
import time
import os
import shutil

from autogluon.multimodal.utils.misc import shopee_dataset
from autogluon.multimodal import MultiModalPredictor

def main():
    download_dir = './ag_automm_tutorial_imgcls'
    train_data_byte, test_data_byte = shopee_dataset(download_dir, is_bytearray=True)
    model_path = f"./tmp/automm_shopee"
    if os.path.exists(model_path):
        shutil.rmtree(model_path)
    predictor = MultiModalPredictor(label="label", path=model_path)
    tic = time.time()
    predictor.fit(
        train_data=train_data_byte, # you can use train_data_byte as well
        time_limit=30, # seconds
    ) # you can trust the default config, e.g., we use a `swin_base_patch4_window7_224` model
    print(f"elapsed (fit): {(time.time()-tic)*1000:.1f} ms")

if __name__=="__main__":
    main()
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by tonyhoo — APPROVED** [review]
LGTM! Great findings in short period of time. Thanks for the investigation and fix

**Review by sxjscience — APPROVED** [review]
Removing the `num_workers` flag is sensible. It also avoids certain multi-processing issues.

**Review by zhiqiangdon — COMMENTED** [review]
I think 0.5.x also used `env.num_workers=2`. Could you check it? I have some doubts on the cause.

**Review by zhiqiangdon — COMMENTED** [review]
Per the offline discussion with @liangfu, the root cause of issue needs more investigations. I will take a look at this.

**Comment by liangfu** [comment]
Canceling this PR for now, in favor of #2776

**Pull request closed without merging**
