### PR TITLE
[AutoMM] Modify the default of basic fine-tuning tricks

### PR DESCRIPTION
**Pull request by Harry-zzh**
*Issue #, if available:*

*Description of changes:*

- Not to convert the categorical features to text.
- Use text augmentation.
- Increase the number of training epochs.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |
| botocore==1.34.97 | botocore==1.34.98 |
| orjson==3.10.2 | orjson==3.10.3 |
| boto3==1.34.97 | boto3==1.34.98 |
| ruff==0.4.2 | ruff==0.4.3 |
| tifffile==2024.4.24 | tifffile==2024.5.3 |
| botocore==1.34.97 | botocore==1.34.98 |
| orjson==3.10.2 | orjson==3.10.3 |
| boto3==1.34.97 | boto3==1.34.98 |
| ruff==0.4.2 | ruff==0.4.3 |
| tifffile==2024.4.24 | tifffile==2024.5.3 |

**Review by zhiqiangdon — APPROVED** [review]
LGTM

**Pull request merged**
