### PR TITLE
Create python-package-conda.yml

### PR DESCRIPTION
**Pull request by b3po345**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |
| types-setuptools==69.5.0.20240513 | types-setuptools==69.5.0.20240518 |
| types-setuptools==69.5.0.20240513 | types-setuptools==69.5.0.20240518 |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |

**Comment by Innixma** [comment]
Hello @b3po345, can you please provide a description of this PR and its intent?

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |
| types-setuptools==69.5.0.20240519 | types-setuptools==69.5.0.20240522 |
| types-setuptools==69.5.0.20240519 | types-setuptools==69.5.0.20240522 |

**Pull request closed without merging**
