### PR TITLE
Upgrade to torch 2.2 and update CI images

### PR DESCRIPTION
**Pull request by prateekdesai04**
*Issue #, if available:*

*Description of changes:*
This is a PR similar to https://github.com/autogluon/autogluon/pull/4118
But includes the updated image changes, and these images are also built and pushed to AG's ECR repo which will be used by the CI.
Pre-this PR CI was having Torch 2.1 + cu121 for GPU and Torch 2.1 for CPU
Post-this PR CI has Torch 2.2 + cu12.1 for GPU and Torch 2.2 for CPU

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |
| botocore==1.34.88 | botocore==1.34.89 |
| boto3==1.34.88 | boto3==1.34.89 |
| botocore==1.34.88 | botocore==1.34.89 |
| boto3==1.34.88 | boto3==1.34.89 |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |
| botocore==1.34.107 | botocore==1.34.108 |
| boto3==1.34.107 | boto3==1.34.108 |
| botocore==1.34.107 | botocore==1.34.108 |
| boto3==1.34.107 | boto3==1.34.108 |

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |
| pytorch-lightning==2.2.4 | pytorch-lightning==2.1.4 |
| torchvision==0.17.2 | torchvision==0.16.2 |
| annotated-types==0.6.0 | annotated-types==0.7.0 |
| triton==2.2.0 | triton==2.1.0 |
| torch==2.2.2 | torch==2.1.2 |
| nvidia-nccl-cu12==2.19.3 | nvidia-nccl-cu12==2.18.1 |
| transformers==4.39.3 | transformers==4.38.2 |
| pytorch-lightning==2.2.4 | pytorch-lightning==2.1.4 |
| torchvision==0.17.2 | torchvision==0.16.2 |
| annotated-types==0.6.0 | annotated-types==0.7.0 |
| triton==2.2.0 | triton==2.1.0 |
| torch==2.2.2 | torch==2.1.2 |
| nvidia-nccl-cu12==2.19.3 | nvidia-nccl-cu12==2.18.1 |
| transformers==4.39.3 | transformers==4.38.2 |

**Review by Innixma — APPROVED** [review]
LGTM! Thanks @prateekdesai04 and @tonyhoo for diving into this and coming up with a solution for mmdet incompatibility!

**Comment by yinweisu** [comment]
| Previous CI Run | Current CI Run |
| :---: | :---: |
| botocore==1.34.109 | botocore==1.34.110 |
| boto3==1.34.109 | boto3==1.34.110 |
| botocore==1.34.109 | botocore==1.34.110 |
| boto3==1.34.109 | boto3==1.34.110 |

**Pull request merged**
