### PR TITLE
codespell: action, config + some typos fixed

### PR DESCRIPTION
**Pull request by yarikoptic**
I saw that there was a recent glorious release.  so I have decided to contribute to make the next one even more glorious ;)  From now on `codespell` action would warn you if a known typo introduced to the code base.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yinweisu** [comment]
@yarikoptic Thanks for the contribution!
Will the workflow just fail and show each typo if there's one?

**Comment by yarikoptic** [comment]
Yes

**Review by Innixma — APPROVED** [review]
This looks great, thanks for the contribution!

**Comment by Innixma** [comment]
@gradientsky shall we merge?

**Review by gradientsky — APPROVED** [review]

**Review by Innixma — APPROVED** [review]
Thanks for the contribution!

**Review by yinweisu — APPROVED** [review]
I think we can merge this in. Thanks!

**Pull request merged**
